# Generated by Django 4.1.6 on 2023-05-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
