# Generated by Django 4.1 on 2022-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocatedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobilenumber', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('advocatetype', models.CharField(max_length=20)),
                ('idproof', models.ImageField(default='null.jpg', upload_to='Image')),
                ('password', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
