# Generated by Django 4.1 on 2022-10-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate_app', '0002_rename_idproof_advocatedb_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocatedb',
            name='district',
            field=models.CharField(default='', max_length=20),
        ),
    ]
