# Generated by Django 4.1 on 2022-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawid', models.IntegerField(default=0)),
                ('lawtype', models.CharField(max_length=20)),
                ('lawname', models.CharField(max_length=20)),
                ('lawdescription', models.CharField(max_length=20)),
            ],
        ),
    ]
