# Generated by Django 4.1 on 2022-10-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsdb',
            name='lawdescription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lawsdb',
            name='lawid',
            field=models.IntegerField(),
        ),
    ]
