# Generated by Django 4.1 on 2022-10-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_alter_lawsdb_lawdescription_alter_lawsdb_lawid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawsdb',
            name='lawid',
        ),
    ]
