# Generated by Django 4.1 on 2022-10-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0005_ipcsections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsdb',
            name='lawdescription',
            field=models.CharField(max_length=1000),
        ),
    ]
