# Generated by Django 4.1 on 2022-10-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(default='', max_length=20)),
                ('mobilenumber', models.IntegerField()),
                ('emailid', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='null.jpg', upload_to='Image')),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
