# Generated by Django 4.1 on 2022-10-05 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0004_law'),
        ('Advocate_app', '0003_advocatedb_district'),
        ('User_app', '0002_rename_place_userdb_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoodAdvocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', max_length=50)),
                ('update', models.CharField(default='', max_length=50)),
                ('advocateid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Advocate_app.advocatedb')),
                ('lawid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_app.lawsdb')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User_app.userdb')),
            ],
        ),
    ]
