# Generated by Django 4.1 on 2022-10-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_remove_bookadvocatedb_lawid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookadvocatedb',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
