# Generated by Django 4.1 on 2022-10-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0007_bookadvocatedb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookadvocatedb',
            name='Room',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookadvocatedb',
            name='update',
            field=models.CharField(default='Not Viewed by advocate', max_length=50),
        ),
    ]
